### ISSUE TITLE
Support of external USB-Drives

### ISSUE THREAD

**Issue by andreasunteidig** [mazi-project/back-end#2]
It would be great if we could

a) connect an external harddrive/usb-stick as an extension. This would be particularly interesting in an archive situation, in which we have large amounts of data and need better data security than provided by the SD card,

b) upload files to owncloud from a usb-stick

**Comment by andreasunteidig** [comment]
This could also be very useful as a backup-solution (adding a function to simply mirror the content on a usb-drive).

**Comment by haniavis** [comment]
This feature is added in v2.5.4.
