### ISSUE TITLE
Support for Python3 in mazi-sense.sh

### ISSUE THREAD

**Issue by paul-maher** [mazi-project/back-end#3]
Some of the sensor code that I have in /root/back-end/lib runs better in Python3. It looks like in mazi-sense.sh it defaults to python. Can we have some sort of configuration option to have it optionally use Python3 to run the sensor programs? 

Or do you have any other suggestions how to achieve this?

**Comment by haniavis** [comment]
Since v3 python defaults to python 2.7 and python3 defaults to python 3.5.3
