### ISSUE TITLE
Shell script locations documentation

### ISSUE THREAD

**Issue by aliblackwell** [mazi-project/back-end#4]
The documentation for all the different backend scripts is great, but it's not clear where in the pi's filesystem the shell scripts are. Updating the documentation to reflect this would be great!

**Comment by iomavridis** [comment]
Hi, Ali  
  I have just updated the documentation of the back-end. The back-end's script location has been included. Thanks for your feedback . 

Regards, John

**Comment by aliblackwell** [comment]
Thanks so much!
